version: '3'
services:
  db:
    image: mariadb:10.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS

  backend:
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: db
    volumes:
      - 'vendor:/var/www/html/vendor'

  composer:
    build:
      context: .
      dockerfile: composer.Dockerfile
    restart: 'no'
    command: 'composer install --no-dev -o -n --no-cache --prefer-dist'
    volumes_from:
      - backend

  migrations:
    build:
      context: .
      dockerfile: migrations.Dockerfile
    restart: 'no'
    env_file: .env
    environment:
      DB_HOST: db

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8000:80'

volumes:
  vendor:
